### ISSUE TITLE
Sticker Mule to In-Kind Sponsor

### ISSUE THREAD

**Issue by tepkenvannkorn** [wcasia/theme-2020#55]
https://www.figma.com/file/vDNpJTFZmNsMFQnwFNXs5M/WordCamp-Asia-2020-Website?node-id=134%3A35

**Comment by tepkenvannkorn** [comment]
Need sponsor team to add copy

**Comment by drebbits** [comment]
This is not yet ready. Sponsor team will reach out when they ready to build the In Kind sponsors area.

**Comment by tepkenvannkorn** [comment]
Text:
Sticker Mule is the fastest and easiest way to buy custom printed products. Order in 60 seconds and we'll turn your designs and illustrations into custom stickers, magnets, buttons, labels and packaging in days. We offer free online proofs, free worldwide shipping and super fast turnaround. https://www.stickermule.com/supports/wordcamps

**Comment by drebbits** [comment]
@tepkenvannkorn we will use Sponsors block moving forward. Use the branch `feature/sponsors-blocks` instead of master for now to update the In-Kind Sponsors.

- [x] Update Sticker Mule single sponsor page with the updated text (keep it in draft)
- [x] Add In-Kind Sponsor at the bottom in the new Sponsors page (https://2020.asia.wordcamp.org/wp-admin/post.php?post=13349&action=edit) (similar structure as the others: heading and the Sponsors block)
- [x] Add class `has-grid-columns-6` to In-Kind Sponsors block, so we could override the grid count for In-Kind Sponsors to 6 per row ([see this diff](https://github.com/wcasia/theme-2020/pull/58/files#diff-b6fc2c408b5230cee5457ce1035cc6b4R1622).

Can you look into publishing a Sponsor without being added in the current Sponsors page (https://2020.asia.wordcamp.org/sponsors/). This is so we could test adding a sponsor in the In-Kind sponsor.

**Comment by tepkenvannkorn** [comment]
Hi @drebbits should this ticket be closed?

**Comment by drebbits** [comment]
@tepkenvannkorn let's go ahead and close this out. We will keep track of the deployment of our changes here in the main Sponsors ticket task.
