### ISSUE TITLE
Can we highlight an error field which is required to fill?

### ISSUE THREAD

**Issue by imnok** [wcasia/theme-2020#59]
There is a notification error message to remind the user to complete all required fields. Can we improve by highlight those fields as well?

I attached the file as an example.

<img width="981" alt="Screen Shot 2019-11-22 at 15 43 01" src="https://user-images.githubusercontent.com/6683477/69411556-cc4e3680-0d3f-11ea-978b-58ae80349b48.png">

**Comment by drebbits** [comment]
@appsrex can you look into this? I'm thinking if it's easy to accomplish, let's do it. If not, let's see if it still worth doing it like do we still have enough tickets to sell, etc.

**Comment by drebbits** [comment]
We can close this one now since we remove required setting for this field. This field added later when many have purchased their ticket already, and it's causing the ticket edit information disappear from their ticket info page.

However, this is a good improvement to keep in mind for better experience in filling out the form for future WordCamps (Asia and other WordCamps).
